acdh-oeaw/viecpro-backend-devops

viecpro_typesense/collections.py

fix: remove facet from model

---

viecpro_typesense/collections.py

fix: add ampel as facet to search

---

viecpro_typesense/clients.py

fix: let us override the remote typesense protocol

---

viecpro_typesense/collections.py

fix: don't make the alternative names a facet

---

viecpro_typesense/handlers.py

fix: use set comprehension to remove duplicates

---

viecpro_typesense/collections.py

fix: add start_date_int and end_date_int

---

viecpro_typesense/collections.py
viecpro_typesense_detail/details/utils.py

fix: ampel should show "red" as default

---

viecpro_typesense/handlers.py
viecpro_typesense_detail/details/utils.py

fix: don't return str(None)

---

viecpro_typesense_detail/details/utils.py

fix: fix another occurrence of string

---

.gitignore

fix(gitignore): add typesense-schemata folder

---

viecpro_typesense_detail/details/detail_person.py

fix: add personplace relations to person

---

viecpro_typesense/classes/collections.py

skip entities that are in collection vorfinale einträge and that
have ampel status red; skip entities that are in the dubletten
collection.
Closes: #54
[skip ci]

fix(import): skip entities

---

viecpro_typesense_detail/details/detail_person.py

fix: add allowance field to person detail

---

viecpro_typesense_detail/details/detail_court.py
viecpro_typesense_detail/details/detail_event.py
viecpro_typesense_detail/details/detail_institution.py
viecpro_typesense_detail/details/detail_person.py
viecpro_typesense_detail/details/detail_place.py

fix: add sameAs links to details

---

viecpro_typesense_detail/details/detail_person.py

fix: add more labels to "Sonstiger Hofbezug"

---

viecpro_typesense_detail/details/detail_person.py

fix: add more variants of "Ehenamen" to married_names

---

viecpro_typesense_detail/details/detail_person.py

fix: sort the `honory_titles` for `label_type` before adding to index

---

viecpro_typesense_detail/details/detail_person.py

fix: add labeltype to non_court_functions

---

viecpro_typesense/classes/collections.py

fix: check if `collection` attribute exists

---

viecpro_typesense/collections.py
viecpro_typesense/handlers.py

fix: add a zotero cache and fix wrong url field

---

viecpro_typesense_detail/details/utils.py

fix: add unix timestamps for relation dates

---

typesense_2025/collections.py

this makes the person.first-name field in typesense sortable

fix: allow sorting by person first-name

---

apis_core/apis_entities/models.py

resolves #156
typo in the merge function prevented the copy

fix: copy labels to new entity

---

apis_core/apis_entities/models.py

resolves #161
copies references to merged entry

fix: copy and dedup references

---

apis_core/apis_entities/models.py

fix: move new and merged entries to cols
